import React from "react";
import Navbar from "./components/navbar";
import {Metadata} from "next";

export const metadata :Metadata = {
    title: 'Next Page',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Navbar/>
                {children}
            </body>
        </html>
    )
}
